services:
  puppies:
    networks:
      - promty
    build: puppy
    hostname: puppy
    stop_signal: SIGINT
    volumes:
      - /dev/shm/puppy-temp:/tmpfs
      - ./cache:/cache
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  proxy:
    networks:
      - promty
    container_name: proxy
    build: proxy

  caddy:
    networks:
      - promty
    container_name: caddy
    build: caddy
    volumes:
      - ./caddy:/etc/caddy
    ports:
      - 80:80

networks:
  promty:
    name: promty
