services:
  puppies:
    networks:
      - promty
    build: puppy
    ports:
      - "127.0.0.1:9000-9002:80"
    stop_signal: SIGINT
    volumes:
      - /dev/shm/puppy-temp:/tmpfs
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  proxy:
    networks:
      - promty
    container_name: proxy
    build: proxy

  caddy:
    networks:
      - promty
    container_name: caddy
    image: caddy:2.8-alpine
    volumes:
      - ./caddy:/etc/caddy
    ports:
      - 80:80

networks:
  promty:
    name: promty
