services:
  puppies:
    networks: [promty]
    build: puppy
    hostname: puppy
    volumes:
      - /dev/shm/puppy-temp:/tmpfs
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      update_config:
        order: start-first

  proxy:
    networks: [promty]
    container_name: proxy
    build: proxy
    depends_on:
      puppies:
        condition: service_healthy

  caddy:
    networks: [promty]
    container_name: caddy
    build: caddy
    volumes:
      - ./caddy:/etc/caddy
    depends_on: [proxy]
    ports:
      - 80:80
      - 9000:9000

networks:
  promty:
    name: promty
